# Generated by Django 3.2.18 on 2023-05-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societylist',
            old_name='date',
            new_name='date_add_society',
        ),
    ]
